export const SALESCENTRI_LINKS = {
      BOOK_DEMO: 'https://salescentri.com/get-started/book-demo',
      FREE_TRIAL_SIGNUP: 'https://salescentri.com/get-started/free-trial',
      CONTACT_FORM: 'https://salescentri.com/get-started/contact',
      CALENDLY_BOOKING: 'https://salescentri.com/get-started/calendly',
      CUSTOMER_PORTAL: 'https://salescentri.com/login/customer-portal',
      PARTNER_PORTAL: 'https://salescentri.com/login/partner-portal',
      PSA_SUITE: 'https://salescentri.com/solutions/psa-suite',
      INTERACTIVE_DEMO: 'https://salescentri.com/solutions/use-case-navigator/demo',
      PRICING: 'https://salescentri.com/pricing',
      PLANS_OVERVIEW: 'https://salescentri.com/pricing/plans-overview',
      ENTERPRISE_CUSTOM: 'https://salescentri.com/pricing/enterprise-custom',
      FREE_TRIAL: 'https://salescentri.com/pricing/free-trial',
      CAREERS: 'https://salescentri.com/company/careers',
      PARTNERS_AFFILIATES: 'https://salescentri.com/company/partners-affiliates',
      CONTACT: 'https://salescentri.com/contact',
      SALES_INQUIRY: 'https://salescentri.com/contact/sales-inquiry',
      SUPPORT_REQUEST: 'https://salescentri.com/contact/support-request',
      PARTNERSHIPS: 'https://salescentri.com/contact/partnerships',
      REQUEST_QUOTE: 'https://salescentri.com/contact/sales-inquiry/request-quote',
      SUBMIT_TICKET: 'https://salescentri.com/contact/support-request/submit-ticket',
      LIVE_CHAT: 'https://salescentri.com/contact/support-request/live-chat',
      PARTNER_INQUIRY: 'https://salescentri.com/contact/partnerships/partner-inquiry',
      INTEGRATION_REQUESTS: 'https://salescentri.com/contact/partnerships/integration-requests',
      PSA_OVERVIEW: 'https://salescentri.com/solutions/psa-suite/overview',
      PSA_FEATURES: 'https://salescentri.com/solutions/psa-suite/features',
      PSA_PRICING: 'https://salescentri.com/solutions/psa-suite/pricing',
      PSA_INTEGRATIONS: 'https://salescentri.com/solutions/psa-suite/integrations',
      PSA_SUCCESS_STORIES: 'https://salescentri.com/resources/case-studies/psa',
      INDUSTRY_IT: 'https://salescentri.com/solutions/by-industry/it',
      INDUSTRY_HEALTHCARE: 'https://salescentri.com/solutions/by-industry/healthcare',
      USE_CASE_SDR: 'https://salescentri.com/solutions/by-use-case/sdr-teams',
      USE_CASE_NAVIGATOR: 'https://salescentri.com/solutions/use-case-navigator',
      CUSTOM_RECOMMENDATIONS: 'https://salescentri.com/solutions/use-case-navigator/recommendations',
      PLATFORM_AI_AGGREGATOR: 'https://salescentri.com/platforms/contact-intelligence/ai-aggregator',
      AI_AGGREGATOR_OVERVIEW: 'https://salescentri.com/platforms/contact-intelligence/ai-aggregator/overview',
      LEAD_GENERATION: 'https://salescentri.com/platforms/lead-management/lead-generation',
      VOICE_AI_AGENT: 'https://salescentri.com/platforms/lead-management/voice-ai-agent',
      CHAT_BOT: 'https://salescentri.com/platforms/lead-management/chat-bot',
      WHATSAPP_BOT: 'https://salescentri.com/platforms/lead-management/whatsapp-bot',
      SERVICE_DATA_ENRICHMENT: 'https://salescentri.com/services/data-enrichment',
      SERVICE_SDR: 'https://salescentri.com/services/sdr-service',
      CASE_STUDIES: 'https://salescentri.com/resources/case-studies',
      WHITEPAPERS: 'https://salescentri.com/resources/whitepapers-ebooks',
      TUTORIALS: 'https://salescentri.com/resources/tutorials-webinars',
      DOCS_USER_GUIDE: 'https://salescentri.com/docs/user-guide',
      API_REFERENCE: 'https://salescentri.com/docs/api-reference',
      SECURITY_PRIVACY: 'https://salescentri.com/trust/security-privacy',
      CERTIFICATIONS: 'https://salescentri.com/trust/compliance-certifications',
      ABOUT_US: 'https://salescentri.com/company/about-us',
      LEADERSHIP_TEAM: 'https://salescentri.com/company/about-us/leadership-team',
      CAREER_OPENINGS: 'https://salescentri.com/company/team-advisors/career-openings',
    };

    export const LOCAL_LINKS = {
      HOME: '/',
      FEATURES: '/features',
      PRICING: '/pricing',
      ABOUT: '/about',
      CONTACT: '/contact',
      BLOG: '/blog',
      FAQ: '/faq',
      BLOG_POST: '/blog/:slug', // Example for dynamic route
      PRIVACY_POLICY: '/privacy-policy',
      TERMS_OF_SERVICE: '/terms-of-service',
    };
